"""ensure user reset token unique

Revision ID: 3c6f07d66775
Revises: 20250818_0007
Create Date: 2025-08-20 20:31:48.921440
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3c6f07d66775'
down_revision = '20250818_0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotes_token', table_name='quotes')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(None, 'users', ['reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_quotes_token', 'quotes', ['token'], unique=1)
    # ### end Alembic commands ###
