name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare artifacts directory
        run: mkdir -p artifacts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Lint frontend
        run: npm run lint | tee artifacts/frontend-lint.log

      - name: Test frontend
        run: npm test -- --run | tee artifacts/frontend-test.log

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: backend/requirements.txt

      - name: Install Python dependencies
        run: pip install -r backend/requirements.txt

      - name: Test backend
        run: pytest | tee artifacts/backend-test.log

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: nexora-frontend:ci
          load: true
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend

      - name: Save frontend image
        run: docker save nexora-frontend:ci -o artifacts/frontend-image.tar

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile
          tags: nexora-backend:ci
          load: true
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend

      - name: Save backend image
        run: docker save nexora-backend:ci -o artifacts/backend-image.tar

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: artifacts

